openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: Local server
  url: http://localhost:8080/v1
security:
- {}
tags:
- description: not yet ready
  name: sdsd
paths:
  /sdsd:
    post:
      operationId: createsdsd
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sdsd'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sdsd'
          description: seccessful operation
      summary: Creates the data
      tags:
      - sdsd
      x-eov-operation-handler: controllers/SdsdController
  /sdsd/{sdsdId}:
    delete:
      operationId: deletesdsd
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: sdsdId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - sdsd
      x-eov-operation-handler: controllers/SdsdController
    get:
      operationId: getsdsd
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: sdsdId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sdsd'
          description: seccessful operation
      summary: Get the element
      tags:
      - sdsd
      x-eov-operation-handler: controllers/SdsdController
    put:
      operationId: updatesdsd
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: sdsdId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sdsd'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sdsd'
          description: seccessful operation
      summary: Updates the element
      tags:
      - sdsd
      x-eov-operation-handler: controllers/SdsdController
  /sdsd/getAll:
    get:
      operationId: getAllsdsd
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/sdsd'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - sdsd
      x-eov-operation-handler: controllers/SdsdController
components:
  schemas:
    sdsd:
      example:
        test: test
        _id: _id
      properties:
        _id:
          type: string
        test:
          type: string
      required:
      - test
      type: object
